[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "shared"
version = "0.1.0"
dependencies = [
    "pyjwt[crypto]>=2.8.0",
    # your other shared dependencies
]